### ISSUE TITLE
Not compatible with netstandart2.0

### ISSUE THREAD

**Issue by NikasZalias** [tpeczek/Demo.AspNetCore.PushNotifications#1]
Could you please make it compatible with .NETStandard, Version=v2.0?

**Comment by tpeczek** [comment]
As this demo evolves I'm planning change of dependencies which should result in being compatible with .NET Standard

**Comment by tpeczek** [comment]
The demo now uses [Lib.Net.Http.WebPush](https://github.com/tpeczek/Lib.Net.Http.WebPush) which provides a fully .Net Standard (>= 1.6) compatible push service client.
