### ISSUE TITLE
Running the demo project after download

### ISSUE THREAD

**Issue by parker-dean** [tpeczek/Demo.AspNetCore.PushNotifications#11]
I downloaded and ran this package and it uses core 2.2.0 and when I run it the following error shows up.

System.FormatException: 'The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.'

public class Program
    {
        public static void Main(string[] args)
        {
            **CreateWebHostBuilder(args).Build().Run();**
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>();
    }

**Comment by tpeczek** [comment]
The project requires some configuration. Take a look inside *appsettings.json*:

```json
{
  "ConnectionStrings": {
    "PushSubscriptionSqliteDatabase": "Filename=./../pushsubscription.db"
  },
  "PushServiceClient": {
    "Subject": "https://localhost:65506/",
    "PublicKey": "<Application Server Public Key>",
    "PrivateKey": "<Application Server Private Key>"
  }
}
```

You need to provide public and private key. There are some generators available online (https://web-push-libs.github.io/vapid/js/)or you can use Node.js to do it (https://rossta.net/blog/using-the-web-push-api-with-vapid.html).

**Comment by parker-dean** [comment]
Thanks for your help on this.

**Comment by krptodr** [comment]
This still happens when using the generators online. Can you provide specific details on  using the vapid generator?

**Comment by tpeczek** [comment]
Hi @krptodr,

It looks like the online generator above is now providing keys in different format. I would suggest using the Node.js one. You can find detailed instructions here: https://www.telerik.com/blogs/push-notifications-in-asp-net-core-with-angular#preparing-asp.net-core-backend-for-push-notifications
