### ISSUE TITLE
 "notificationclick" not triggering in Chrome Version 92.0.4515.159 (Official Build) (64-bit)

### ISSUE THREAD

**Issue by httt-dev** [tpeczek/Demo.AspNetCore.PushNotifications#16]
I try edit self.addEventListener('notificationclick', function (event)  to open browser when click on notification but it seem "notificationclick" event not firing .

```
self.addEventListener('notificationclick', function (event) {
    console.log("notificationclick trigger");
    let urlExam = 'https://google.com/';
    event.notification.close(); 
    event.waitUntil(
        clients.matchAll({ type: 'window' }).then(windowClients => {
            // Check if there is already a window/tab open with the target URL
            for (var i = 0; i < windowClients.length; i++) {
                var client = windowClients[i];
                // If so, just focus it.
                if (client.url === url && 'focus' in client) {
                    return client.focus();
                }
            }
            // If not, then open the target URL in a new window/tab.
            if (clients.openWindow) {
                return clients.openWindow(urlExam);
            }
        })
    );
});
```

I also try on edge and notificationclick event trigger success. 
I've tried using the Chrome debugger, and I can set a break point in the code that shows the notification, but all breakpoints within the notificationclick handler fail to pause execution.
I've spent days trying to get this to work but ....do you know why not working on chrome ? Please help me .

**Comment by tpeczek** [comment]
Hi @httt-dev,

Yes, this event sometimes acts funky in Chrome. The most common development time issue is that Chrome is not actually using the code you think for the Service Worker. An important practice when working with Service Workers in Chrome is to always remove the Service Worker manually from Chrome DevTools.

Other than that I did encounter some timing issues in weird scenarios but nothing I could call a pattern.

**Comment by httt-dev** [comment]
I understood the problem of chrome. Thanks for feedback.
