### ISSUE TITLE
Support for decryption of incoming web push payload?

### ISSUE THREAD

**Issue by HamidZaeri** [tpeczek/Demo.AspNetCore.PushNotifications#19]
Hi @tpeczek 

Is it possible to decrypt a web push payload as .NET client?

I mean, after sending a web push and upon receiving in a C# client?

**Comment by tpeczek** [comment]
Hi @HamidZaeri,

I'm not sure if I understand the scenario you have in mind, can you describe it in more details?

**Comment by HamidZaeri** [comment]
Sure, this is my [SO topic](https://stackoverflow.com/questions/77758132/decryption-of-incoming-web-push-messages-in-net) regarding my problem.

I almost dig the whole net, but couldn't find a thing to decrypt a [web push](https://datatracker.ietf.org/doc/html/draft-ietf-webpush-encryption) payload for .NET.

**Comment by tpeczek** [comment]
Ok, I'll try to navigate this a little bit, although I'm not entirely sure if your context is clear to me.

Let's start with WebPush. The "[Message Encryption for Web Push](https://www.rfc-editor.org/rfc/rfc8291)" in fact describes how to use "[Encrypted Content-Encoding for HTTP](https://www.rfc-editor.org/rfc/rfc8188)" in context of Web Push. I do have a library (which I use as a dependency here) which provides encryption and decryption inline with "Encrypted Content-Encoding for HTTP", it's [Lib.Net.Http.EncryptedContentEncoding](https://github.com/tpeczek/Lib.Net.Http.EncryptedContentEncoding). If what you really want to decrypt is a WebPush message, you could do that with help of that library, you would just need to provide the keying material (based on "Message Encryption for Web Push" you could adopt the code from this library: https://github.com/tpeczek/Lib.Net.Http.WebPush/blob/722cc01cc21059f75742dc14906b3fe167ac7112/src/Lib.Net.Http.WebPush/PushServiceClient.cs#L285).

That said, after quick glimpse at the Telegram docs, you might be getting something different than WebPush payload, so you need to be sure that you are looking at the right thing.

**Comment by HamidZaeri** [comment]
I couldn't find how to decrypt a web push in your links. Could you give me an example?

But let me describe the scenario a little more:

1- I have a Telegram client running on an ASP.NET server.

2- I [register a web push device with Telegram](https://core.telegram.org/method/account.registerDevice) by providing an `endpoint`, a `p256dh` public key and an `auth` ([here is the code, how I generated them](https://stackoverflow.com/questions/77758132/decryption-of-incoming-web-push-messages-in-net)).

3- Telegram handle the encryption part and sends the encrypted notifications to my `endpoint` URL (which is on the same ASP.NET server).

4- Finally, I receive notifications at my endpoint in an encrypted form.
Here is an example of an incoming notification coming from Telegram:

Request Headers:
> Content-Encoding: **aesgcm**
> Encryption: **salt=aQq1xjPD4RTD7UQ-xAwB7Q**
> Crypto-Key: **dh=BOVgNTu5ncaG-eycXbmIVzNonV1uDYL0FG4cojjUm-j3Dg_u4Af-qLEDc4QRknBDxqeiNuqjVi8bzkWvkx14eaQ**
> Urgency: high
> TTL: 2419200
> Content-Type: application/octet-stream
> Content-Length: 305

Request Body is an encrypted byte array, which I should use above headers and probably `p256dh` key to decrypt it, but don't know how to do it.

**Comment by tpeczek** [comment]
I don't have a ready to use code as I never needed one. That said everything you need is in the referenced materials, you just need to put it together.

The mentioned [Lib.Net.Http.EncryptedContentEncoding](https://github.com/tpeczek/Lib.Net.Http.EncryptedContentEncoding) provides [`Aes128GcmEncoding.DecodeAsync`](https://tpeczek.github.io/Lib.Net.Http.EncryptedContentEncoding/api/Lib.Net.Http.EncryptedContentEncoding.Aes128GcmEncoding.html#Lib_Net_Http_EncryptedContentEncoding_Aes128GcmEncoding_DecodeAsync_System_IO_Stream_System_IO_Stream_System_Func_System_Byte___System_Byte____) method for you. That method will decrypt a request body coming in  "[Encrypted Content-Encoding for HTTP](https://www.rfc-editor.org/rfc/rfc8188)" format (which is indicated by `Content-Encoding: aesgcm` header). What you need to implement by yourself, is the `keyProvider` (either `Func<Byte[], Byte[]>` or `Func<string, byte[]>`).

Now, when it comes to how to implement the `keyProvider`, I'm not sure if Telegram fully follows "[Message Encryption for Web Push](https://www.rfc-editor.org/rfc/rfc8291)", it might be just using "[Encrypted Content-Encoding for HTTP](https://www.rfc-editor.org/rfc/rfc8188)" and it simply uses the `secret` which you have provided during registration of the device as the key. I might be wrong (I've just quickly skimmed through the documentation) but if I'm right, the key provider might be as simple as `(keyId) => secret`. If I'm wrong, than it means you have to base your implementation on section 3.4 of  "[Message Encryption for Web Push](https://www.rfc-editor.org/rfc/rfc8291)"  - what would be needed from that pseudocode is the IKM. If you would end up in that second scenario, the [`GetKeyingMaterial`](https://github.com/tpeczek/Lib.Net.Http.WebPush/blob/722cc01cc21059f75742dc14906b3fe167ac7112/src/Lib.Net.Http.WebPush/PushServiceClient.cs#L319) method that you can find in [Lib.Net.Http.WebPush](https://github.com/tpeczek/Lib.Net.Http.WebPush) is implementation of that pseudocode for the application server, so you can just adjust it as you are acting as user agent in your case.

Btw. I believe you are ignoring authentication in your implementation - you should authenticate who is sending the notification.

**Comment by tpeczek** [comment]
After taking one more look at the headers you have included, my second suspicion is that Telegram might be using a legacy/deprecated version of "Encrypted Content-Encoding for HTTP". It might be [version 03](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-encryption-encoding-03) or lower as those are the only ones using the `Encryption` HTTP header. Those old versions are in fact not supported by WebPush and I don't remember when was the last time I saw any of them in the wild.

If that is the case, none of the above code will work as the decryption algorithm is different. A dedicated implementation would be needed based on the specification (certainly some of the internal code from [Lib.Net.Http.EncryptedContentEncoding](https://github.com/tpeczek/Lib.Net.Http.EncryptedContentEncoding) could be reused).
