### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by fergalmoran** [tpeczek/Demo.AspNetCore.PushNotifications#7]
First off - thanks for your super helpful blog post and repo.

I've copy/pasted large portions of this code in an open source project of my own and was wondering where I stand on license attribution. Are you happy with a link in my own repo's license file or would you rather attribution in every source file? I've heavily modified a lot of it so that may be problematic but I can certainly do it if that's what you require?

**Comment by tpeczek** [comment]
Does your project uses Lib.Net.Http.WebPush as a dependency and you have copied only the code around it from here, or are you reimplementing Push API client based on what is in Lib.Net.Http.WebPush?

**Comment by tpeczek** [comment]
If I have deduced correctly and project in question is https://github.com/podnoms/podnoms-api, then I can see it has a dependency on  Lib.Net.Http.WebPush and you have been copying only from this demo project directly. In such case notice in your LICENSE file is enough. I would appreciate mention in your README file, but it's not required.

**Comment by fergalmoran** [comment]
You have deduced correctly, README updated - and thanks again!
